### ISSUE TITLE
Symbol conflicts with vendored `openssl` can cause invalid outputs

### ISSUE THREAD

**Issue by DaniPopes** [DaniPopes/keccak-asm#9]
See https://github.com/alloy-rs/core/issues/711.

---
https://github.com/alloy-rs/core/issues/711#issuecomment-2298830376:

Reduced:

src/main.rs
```rust
extern crate alloy_primitives;
extern crate openssl;

fn main() {
    assert_eq!(
        alloy_primitives::keccak256("testFoo()"),
        alloy_primitives::b256!("79adbd5094e60c1bc2b963678ff44695d1430b8ccff0b1cd57c03a7f63567822"),
    );
}
```

Cargo.toml
```toml
[package]
name = "foundry-zksync-release-debug"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.7", default-features = false }
openssl = { version = "0.10", features = ["vendored"] }

[features]
asm-keccak = ["alloy-primitives/asm-keccak"]
```

---

Running `cargo run --features asm-keccak` panics.

Applying this patch makes the command run fine again:
```diff
diff --git a/src/main.rs b/src/main.rs
index c82c4a9..1ae767f 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,5 +1,5 @@
-extern crate alloy_primitives;
 extern crate openssl;
+extern crate alloy_primitives;
 
 fn main() {
     assert_eq!(
```

---

I am not sure how to fix this, it seems like it's a symbol conflict between the vendored openssl static library and keccak-asm's.
